# -*- coding: utf-8 -*-
"""AI_Ethics_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F8PwmtPaXz7i3d8inK4MM3Ox62fmz27e
"""

import pandas as pd

data = pd.read_csv("CurrentPopulationSurvey.csv")

print(data.head())

print(list(data.columns))

[c for c in data.columns if 'inc' in c.lower() or 'earn' in c.lower() or 'wage' in c.lower()]

print(data['sex'].unique())

best_columns = ['sex', 'race', 'age', 'incwage', 'region', 'metro', 'occ', 'ind', 'educ99']
data = data[best_columns]

print(data.head())
data = data[best_columns].dropna() # educ99 has NaNs in source [1], so dropna is vital
data = data[data['incwage'] > 0]
data['sex'] = data['sex'].replace({1: 'Male', 2: 'Female'})

# Remove missing values
data = data[best_columns].dropna() # educ99 has NaNs in source [1], so dropna is vital
# Remove zero or negative income (invalid)
data = data[data['incwage'] > 0]

data['sex'] = data['sex'].replace({1: 'Male', 2: 'Female'})

print(data['sex'].value_counts())

# NEW: Intersectional Wage Analysis (Gender + Race)
# This proves that ethical issues are multi-layered
intersectional_bias = data.groupby(['sex', 'race'])['incwage'].mean()
print("Average Salary by Gender and Race:")
print(intersectional_bias)

avg_salary = data.groupby('sex')['incwage'].mean()

print("Average Salary by Gender:")
print(avg_salary)

import matplotlib.pyplot as plt

avg_salary.plot(kind='bar')
plt.title("Average Wage by Gender")
plt.ylabel("Income")
plt.show()

# High income threshold
threshold = data['incwage'].median()

data['High_Income'] = data['incwage'] > threshold

bias = pd.crosstab(data['sex'], data['High_Income'])

print(bias)

selection_rate = data.groupby('sex')['High_Income'].mean()

print("Selection Rate (High Income Probability):")
print(selection_rate)

#Biased model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

#Prepare Data
X = data[['sex', 'region', 'metro', 'occ', 'ind', 'educ99']].copy()
X['sex'] = X['sex'].map({'Male': 1, 'Female': 0})
y = data['High_Income']

# 2. Split into Training and Testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Train the Model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# 4. Check for AI Bias in Predictions
predictions = X_test.copy()
predictions['predicted_high_income'] = model.predict(X_test)

print("AI Model Selection Rate (Predicted Probability):")
print(predictions.groupby('sex')['predicted_high_income'].mean())

#Implement Mitigation (Fairness through Blindness)
# 1. Remove the 'sex' column to 'blind' the model
X_blind = X_train.drop(columns=['sex'])
X_test_blind = X_test.drop(columns=['sex'])

# 2. Retrain the 'Blind' Model
blind_model = LogisticRegression(max_iter=1000)
blind_model.fit(X_blind, y_train)

# 3. Check if bias still exists
blind_predictions = X_test.copy() # We keep X_test to check the 'sex' later
blind_predictions['predicted_high_income'] = blind_model.predict(X_test_blind)

print("\n'Blind' Model Selection Rate (Sex column removed):")
print(blind_predictions.groupby('sex')['predicted_high_income'].mean())

#Check the accuracy of the blind model
from sklearn.metrics import accuracy_score

biased_accuracy = accuracy_score(y_test, predictions['predicted_high_income'])
print(f"Biased Model Accuracy: {biased_accuracy:.2%}")

#Final Comparison
blind_accuracy = accuracy_score(y_test, blind_model.predict(X_test_blind))

print(f"Blind Model Accuracy: {blind_accuracy:.2%}")
print(f"Accuracy Lost for Fairness: {biased_accuracy - blind_accuracy:.2%}")

print("\n--- ETHICAL CONCLUSION ---")
print("While the 'Blind' model is less accurate, it successfully eliminated the")
print("absolute bias (1.0 vs 0.0) seen in the first model. This demonstrates the")
print("Accuracy-Fairness trade-off essential in Ethical AI Research.")

import matplotlib.pyplot as plt
import pandas as pd

# Extracting rates from existing results
biased_rates = predictions.groupby('sex')['predicted_high_income'].mean()
blind_rates = blind_predictions.groupby('sex')['predicted_high_income'].mean()

# Summary dataframe for plotting
comparison_df = pd.DataFrame({
    'Biased Model': biased_rates,
    'Blind Model': blind_rates
})

# Rename indices for clarity
comparison_df.index = ['Female', 'Male']

# Plotting the comparison
comparison_df.plot(kind='bar', figsize=(8, 5))
plt.title("Impact of Ethical Mitigation on Selection Rates")
plt.ylabel("Selection Rate (High Income Probability)")
plt.xlabel("Gender")
plt.xticks(rotation=0)
plt.legend(title="Model Type")
plt.show()